---
- name: Fetch secret from HashiCorp Vault
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Vault token from environment variable
      set_fact:
        vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"

    - name: Retrieve secret from Vault
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret/data/mysecret:value', token=vault_token) }}"

