---
- name: Fetch secret from Vault
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Fetch secret from Vault
      ansible.builtin.debug:
        msg: "{{ lookup('hashi_vault', 'secret/data/mysecret:value', token='{{ lookup('hashi_vault', 'VAULT_TOKEN') }}') }}"
